#!/bin/sh
# POSTRM script for goveebttemplogger

echo "`date --rfc-3339='seconds'` \033[36mHI I'M A POSTRM SCRIPT running \033[32m${0}\033[36m as \033[91m`whoami`\033[39m"
systemctl daemon-reload

exit 0