#!/bin/sh
# POSTRM script for goveebttemplogger

echo "\033[36mHI I'M A POSTRM SCRIPT \033[32m${0}\033[36m `date --rfc-3339='seconds'` running as \033[91m`whoami`\033[39m"
systemctl daemon-reload

exit 0