#!/bin/sh
# PRERM script for goveebttemplogger

echo "\033[36m HI I'M A PRERM SCRIPT `date --rfc-3339='seconds'` running as \033[91m`whoami`\033[39m"
systemctl stop goveebttemplogger.service
systemctl disable goveebttemplogger.service

exit 0