#!/bin/sh
# PRERM script for goveebttemplogger

echo "\033[36mHI I'M A PRERM SCRIPT \033[32m${0}\033[36m `date --rfc-3339='seconds'` running as \033[91m`whoami`\033[39m"
systemctl stop goveebttemplogger.service
systemctl disable goveebttemplogger.service

exit 0