#! /bin/bash

### BEGIN INIT INFO
# Provides:          GoveeBTTempLogger
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GoveeBTTempLogger service
# Description:       Run GoveeBTTempLogger service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting GoveeBTTempLogger..."
    /usr/local/bin/goveebttemplogger -v 0 -l /var/log/goveebttemplogger &
    # sudo -u foo-user bash -c 'cd /path/to/scripts/ && ./start-foo.sh'
    ;;
  stop)
    echo "Stopping GoveeBTTempLogger..."
    # sudo -u foo-user bash -c 'cd /path/to/scripts/ && ./stop-foo.sh'
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/goveebttemplogger {start|stop}"
    exit 1
    ;;
esac

exit 0
